### ISSUE TITLE
DifferentialEquations.jl v5.0 and Julia v1.0.0 Compatibility

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DifferentialEquations.jl#318]
Our DiffEq v5.0 release will also be the v0.7.0 compatibility release. The user-facing API changes are quite minimal, though it's v5.0 due to new feature releases and big breaking changes to the solver infrastructure. Here is a set of items which I am deeming as part of the v5.0.

There will be an official release post [on the JuliaDiffEq.org blog roll](https://github.com/JuliaDiffEq/juliadiffeq.github.io/blob/07releasepost/_posts/2018-7-15-FunctionInputEPIRK.md). This post will be very release focus: mentioning exactly what was added and changed. I will also do an ecosystem update summary on my own StochasticLifestyle.com which will be more focused on describing our current trajectory and future goals.

- [x] Refactor N-body tooling to its own package and branding. @Mikhail-Vaganov  
- [x] Refactor internal expv and phiv tools to a usable standalone package  @MSeeker1340
- [ ] Mirror OrdinaryDiffEq nlsolve changes at StochasticDiffEq @YingboMa
- [x] Mirror OrdinaryDiffEq Jacobian changes at StochasticDiffEq @MSeeker1340 
- [x] Finish QNDF and QBDF @sipah00
- [x] Make a decision on https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/264
- [x] Make a decision on https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/310
- [x] Make a decision on #321
- [x] Fix https://github.com/JuliaDiffEq/RecursiveArrayTools.jl/issues/38
- [x] https://github.com/JuliaDiffEq/DiffEqBase.jl/issues/140 @tkf 

Adding warnings in https://github.com/JuliaDiffEq/DiffEqBase.jl/blob/master/src/solve.jl : this is easy stuff and good JuliaCon2018 work:

- [x] Add tests for the new high level interface with things like distributions
- [x] Add high level warnings for integer time with adaptive methods
- [x] Add high level warnings for incorrect use of Dual numbers
- [x] Throw an error if we see a non-common interface argument. @ScottPJones can you help here?
- [ ] Check `saveat` and `tstops` entry: if `[]` then `eltype(prob.tspan)[]`. EDIT: NOT BLOCKING

And here's the v0.7.0 compatibility list. The packages are only marked off after
tests can pass without depwarns due to themselves (and the test depwarns are
cleaned up).

- [x] OrdinaryDiffEq
- [x] StochasticDiffEq
- [x] DelayDiffEq
- [x] DiffEqBase
- [x] DiffEqOperators
- [x] DiffEqProblemLibrary
- [x] DiffEqMonteCarlo
- [x] DiffEqNoiseProcess
- [x] DiffEqFinancial
- [x] DifferentialEquations
- [x] PoissonRandom
- [x] DiffEqUncertainty
- [x] ParameterizedFunctions
- [x] Sundials
- [x] MuladdMacro
- [x] DASKR
- [x] DASSL
- [x] ODEInterfaceDiffEq
- [x] DimensionalPlotRecipes
- [x] RecursiveArrayTools
- [x] ResettableStacks
- [x] MATLABDiffEq
- [x] DiffEqDiffTools
- [x] DiffEqDevTools
- [x] DiffEqCallbacks
- [x] SteadyStateDiffEq
- [x] SimpleDiffEq
- [x] OrdinaryDiffEqExtendedTests
- [x] PyDSTool
- [x] DiffEqPhysics @Mikhail-Vaganov  
- [x] DiffEqSensitivity
- [x] DiffEqJump
- [x] DiffEqBiological
- [x] MultiscaleArrays
- [x] ModelingToolkit
- [x] FEniCS @ysimillides 
- [x] BoundaryValueDiffEq @YingboMa 

Waiting for external authors (not considered blocking):

- BridgeDiffEq
- GeometricIntegratorsDiffEq
- DiffEqBayes
- DiffEqParamEstim

And documentation updates:

- [x] Check the tutorials
- [ ] Update the benchmarks
- [x] Update the devdocs
- [x] Update the docs (add high level interface things)
- [x] Document no-recompile mode
- [ ] Optional: update the webserver to use the new standardized no-recompile mode and v0.7? @amellnik

**Comment by ScottPJones** [comment]
"Throw an error if we see a non-common interface argument"
I won't have time to look until Hackathon at the end of JuliaCon, hopefully we can talk about it there :grinning:

**Comment by ChrisRackauckas** [comment]
@ScottPJones sounds like a plan!

**Comment by ChrisRackauckas** [comment]
DiffEqDevTools has a problematic depwarn:

```julia
┌ Warning: `a::AbstractArray + b::Number` is deprecated, use `a .+ b` instead.
│   caller = top-level scope at none:0
└ @ Core none:0
┌ Warning: `a::AbstractArray + b::Number` is deprecated, use `a .+ b` instead.
│   caller = top-level scope at none:0
└ @ Core none:0
┌ Warning: `a::AbstractArray + b::Number` is deprecated, use `a .+ b` instead.
│   caller = top-level scope at none:0
└ @ Core none:0
┌ Warning: `a::AbstractArray + b::Number` is deprecated, use `a .+ b` instead.
│   caller = top-level scope at none:0
└ @ Core none:0
Now weak error
Get sample errors
Test Summary:              | Pass  Total
Analyticless Stochastic WP |    1      1
179.462133 seconds (478.09 M allocations: 111.873 GiB, 25.36% gc time)
```

**Comment by ChrisRackauckas** [comment]
Every library has been updated.

**Comment by YingboMa** [comment]
`OrdinaryDiffEq` now works on Julia 1.0-rc. (`ForwardDiff#master` and `Parameters.jl` with https://github.com/mauro3/Parameters.jl/pull/68 are needed)

**Comment by ChrisRackauckas** [comment]
v1.0-RC tests passing:

- [ ] OrdinaryDiffEq
- [ ] StochasticDiffEq
- [ ] DelayDiffEq
- [ ] DiffEqBase
- [ ] DiffEqOperators
- [ ] DiffEqProblemLibrary
- [ ] DiffEqMonteCarlo
- [ ] DiffEqNoiseProcess
- [ ] DiffEqFinancial
- [ ] DifferentialEquations
- [ ] PoissonRandom
- [ ] DiffEqUncertainty
- [ ] ParameterizedFunctions
- [ ] Sundials
- [ ] MuladdMacro
- [ ] DASKR
- [ ] DASSL
- [ ] ODEInterfaceDiffEq
- [ ] DimensionalPlotRecipes
- [ ] RecursiveArrayTools
- [ ] ResettableStacks
- [ ] MATLABDiffEq
- [ ] DiffEqDiffTools
- [ ] DiffEqDevTools
- [ ] DiffEqCallbacks
- [ ] SteadyStateDiffEq
- [ ] SimpleDiffEq
- [ ] OrdinaryDiffEqExtendedTests
- [ ] PyDSTool
- [ ] DiffEqPhysics @Mikhail-Vaganov  
- [ ] DiffEqSensitivity
- [ ] DiffEqJump
- [ ] DiffEqBiological
- [ ] MultiscaleArrays
- [ ] ModelingToolkit
- [ ] FEniCS @ysimillides 
- [ ] BoundaryValueDiffEq @YingboMa

**Comment by ChrisRackauckas** [comment]
Update:

- 3 libraries are failing because RandomNumbers.jl needs to tag with `Random.seed!`, but are otherwise working. 
- FEniCS.jl needs to test with the new PyCall. 
- PyDSTool.jl has some mysterious error. 
- DelayDiffEq.jl needs to upgrade to handle new nonlinear solvers
- Need to setup the warnings, that should be quick
- `remake` seems to be type stable if we use the DiffEqFunction, so it should be a quick fix.
- We need to add some things to the docs.

**Comment by ChrisRackauckas** [comment]
I'm checking off PyDSTool since it's a known upstream issue and we need them to tag...

**Comment by tkf** [comment]
`remake` still is not type stable https://github.com/JuliaDiffEq/DiffEqBase.jl/issues/140#issuecomment-414013282

**Comment by ChrisRackauckas** [comment]
We need RandomNumbers.jl to release but other than that nothing else looks blocking. https://github.com/JuliaDiffEq/StochasticDiffEq.jl/pull/99 is the last PR we want done, so it can track on its own. The blog post will go out on Monday either way since it's really not "that" breaking (and we'll just document it as though it's already happened, it should be done by Monday though). The webserver probably needs a bigger update and that's somewhat disconnected from this, and the benchmarks... I need to get the computer up and running again. So cheers.
