### ISSUE TITLE
Performance Meta Issue

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DifferentialEquations.jl#33]
This issue is for tracking places where small performance updates should occur:

- [x] Feagin's update step should become in place. #30 
- [x] ~~Change tableaus to StaticArrays #9, waiting on v0.5 release~~
- [x] Add precompile hinting
- [ ] Improve type-inference on FEM, and make quadrature in-place.
- [ ] Make FEM solvers in place, add wrapper for non-inplace inputs #18 
- [ ] Change cg! and gmres! to really in place #5 
- [ ] Make ParallelAccelerator versions of solvers when v0.5 compatible?
- [x] Make multi-threaded versions of solvers
- [ ] Add Xeon Phi / GPU solvers
- [x] Lund Stabilization
- [ ] Change ChunkedArrays to in-place random generation
- [ ] Try new RNGs from RNG.jl

**Comment by ChrisRackauckas** [comment]
Everything here is covered somewhere else or obsolete from new plans.
